apiVersion: v1
kind: Service
metadata:
  name: {{ include "coverity.fullname" . }}
  labels:
    {{- include "coverity.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: commit
      protocol: TCP
      name: commit
    - port: 8005
      targetPort: control
      protocol: TCP
      name: control
  selector:
    {{- include "coverity.selectorLabels" . | nindent 4 }}
